# fly.toml file generated for gaiabot on 2022-10-24T16:58:31-04:00

app = "gaiabot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
